### ISSUE TITLE
font issue at render time

### ISSUE THREAD

**Issue by j2l** [ubisoft/shotmanager#32] opened 2022-06-22 10:08 UTC
**Infos on the context**
- Add-on version: beta 2
- Blender version, from installer or from zip: 2.93.3 (deb package)
- OS: Ubuntu 21.10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): IDK

**Describe the bug**
![Screenshot from 2022-06-22 12-04-46](https://user-images.githubusercontent.com/65325/175003406-909ad804-3f9f-4a4a-a3a8-c5f89693669d.png)

**To Reproduce**
click render image, or render shot or render all

**Comment by werwack** [comment] 2022-06-23 17:08
Ok, this is a Stamp Info issue, plateform specific. Will see how that can be fixed...

**Comment by werwack** [comment] 2022-08-10 11:55
Hello,
Unfortunately I am not able to reproduce the issue since I cannot have access to a Linux plateform.
I close the issue. Feel free to re-open it in case you have more possible info on the repro case.
Sorry...

**Closed** 2022-08-10 11:56 UTC
Labels: bug, wontfix, os specific
